name = "IceFloeTracker"
uuid = "04643c7a-9ac6-48c5-822f-2704f9e70bd3"
authors = ["bradford roarr <bradford_roarr@brown.edu> and contributors"]
version = "0.1.0"

[deps]
ArgParse = "c7e460c6-2fb9-53a9-8c5b-16f535851c63"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[compat]
julia = "1.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
