$schema: "https://json-schema.org/draft/2020-12/schema"
## First add SPACEUSER and SPACEPSWD to .bash_profile or .zshrc or add to ENV VARS in Windows 
## Or export these in Oscar from command line just before running the snakemake job
startdate: "2022-03-09"
enddate: "2022-03-10"
bounding-box: "81 -23 79 12"
truecolor-outdir: "images/truecolor"
reflectance-outdir: "images/reflectance"
fetchdata-outdir: "images"
landmask-outdir: "output/landmasks"
preprocess-outdir: "output/preprocess"
soit-outdir: "output/soit"
centroid-x: "80"
centroid-y: "-18"