$schema: "https://json-schema.org/draft/2020-12/schema"
## First add SPACEUSER and SPACEPSWD to .bash_profile or .zshrc or add to ENV VARS in Windows 
## Or export these in Oscar from command line just before running the snakemake job
startdate: "2023-02-09"
enddate: "2023-02-11"
bounding-box: "81 -23 79 12"
main-outdir: "output"
truecolor-outdir: "images/truecolor"
reflectance-outdir: "images/reflectance"
fetchdata-outdir: "images"
landmask-outdir: "landmasks"
lm-generated: "landmasks/generated"
soit-outdir: "soit"
centroid-x: "72"
centroid-y: "-18"