executor: slurm
jobs: 16
default-resources:
  slurm_partition: "batch"  
  slurm_account: "default"  # OSCAR: condo account
  runtime: "10m"

set-resources:
  init_ift:
    runtime: "30m"
    mem: "16g"
  segment:
    runtime: "30m"
    mem: "32g"
  tracking:
    runtime: "8h"
    mem: "64g"
  


partitions:
  batch:
    max_runtime: 720
    max_nodes: 1
    max_cpus_per_task: 16
