resources: 
  soit_api_calls: 2

executor: slurm
jobs: 4
default-resources:
  slurm_partition: "batch"  
  slurm_account: "default"  # OSCAR: condo account
  mem_mb_per_cpu: 2000
  runtime: 60  # seconds

partitions:
  batch:
    max_runtime: 720
    max_nodes: 1
    max_cpus_per_task: 16  
