#--------------------------------------------------
# Config files
#--------------------------------------------------
REGION_CSV: configs/validation-cases/validation-region-case-250km.csv # relative to snakefile
CASE_CSV: configs/validation-cases/validation-region-case-250km.csv # relative to snakefile
