$schema: "https://json-schema.org/draft/2020-12/schema"
## First add SPACEUSER and SPACEPSWD to .bash_profile or .zshrc or add to ENV VARS in Windows 
## Or export these in Oscar from command line just before running the snakemake job
## At least two days of data are required for the run 

## Update this block with your area of interest and timeframe
startdate: "2022-02-09"
enddate: "2022-02-10"
bounding-box: "81 -23 79 12"
centroid-x: "80"
centroid-y: "-18"

## Suggest using the default paths below for the workflow
fetchdata-outdir: "images"
truecolor-outdir: "images/truecolor"
reflectance-outdir: "images/reflectance"
landmask-outdir: "output/landmasks"
preprocess-outdir: "output/preprocess"
soit-outdir: "output/soit"
features-outdir: "output/features"
