#--------------------------------------------------
# Executables
#--------------------------------------------------

IFT: julia --project=.julia
FSDPROC: "pipx run --spec git+https://github.com/WilhelmusLab/ebseg@v1.0.1 fsdproc"
PASS_TIME: "pipx run --spec git+https://github.com/wilhelmuslab/satellite-overpass-identification-tool@v3.2.1 satellite-overpass-identification-tool"
LOADER: "pipx run --spec git+https://github.com/brown-ccv/earthdata-downloader@v1.0 earthdata-downloader load"

#--------------------------------------------------
# Config files
#--------------------------------------------------
REGION_CSV: configs/default/region.csv # relative to snakefile
CASE_CSV: configs/default/case.csv # relative to snakefile
PROJECT_TOML: configs/default/Project.toml # relative to snakefile

#--------------------------------------------------
# Satellites
#--------------------------------------------------
SATELLITES: ["aqua", "terra"]

