#--------------------------------------------------
# Config files
#--------------------------------------------------
REGION_CSV: workflow/configs/case-region-file/case_region.csv
CASE_CSV: workflow/configs/case-region-file/case_region.csv
