# Configuration for OSCAR cluster at Brown University

executor: slurm
jobs: unlimited
directory: workflow/results
resources:
  soit_api_calls: 4
default-resources:
  slurm_partition: "batch"
  slurm_account: "default"
  runtime: "10m"
set-resources:
  init_ift:
    runtime: "30m"
    mem: "32g"
    cpus_per_task: 4
  load_coastal_buffer_mask:
    mem: "16g"
  load_landmask:
    mem: "16g"
  get_region_month_overpass_times:
    mem: "8g"
  segment:
    runtime: "2h"
    mem: "32g"
  tracking:
    runtime: "8h"
    mem: "32g"

partitions:
  batch:
    max_runtime: 720
    max_nodes: 1
