name: Test Julia Notebooks

on: [pull_request]

jobs:
  run-notebooks:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version: [1.10]
        arch: [x64, x86]

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: update pip
        run: python -m pip install -U pip
      - name: install python deps
        run: python -m pip install -U -r requirements.txt
      - uses: julia-actions/setup-julia@v2
        with:
          version: ${{ matrix.version }}
          arch: ${{ matrix.arch }}
      - uses: julia-actions/cache@v2
      - uses: julia-actions/julia-buildpkg@v1
        env:
          PYTHON: python
      - name: Run Jupyter Notebooks
        uses: yaananth/run-notebook@v2
        with:
          notebook: 'notebooks/preprocessing-workflow/tiling.ipynb'