# trigger-docker-fetchdata.yml
name: Trigger Docker build - Fetchdata
on:
    push:
        branches:
          - main
jobs:
    trigger_workflow:
      runs-on: ubuntu-latest 
      steps:
        - name: Trigger Fetchdata Docker build
        - uses: convictional/trigger-workflow-and-wait@v1.6.1
          with:
           owner: WilhelmusLab
           repo: ice-floe-tracker-pipeline
           github-token: ${{ secrets.TRIGGER_PAT }}
           workflow_file_name: build-docker-fetchdata.yml
           ref: main
           wait_interval: 30
           propagate_failure: true
           trigger_workflow: true
           wait_workflow: true